/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan;

/**
 *
 * @author lenovo
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnBuku = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnPeminjaman = new javax.swing.JMenuItem();
        mnPengemballian = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnPengunjung = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnTransaksi = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnLapBuku = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnLapPeminjaman = new javax.swing.JMenuItem();
        mnLapPengembalian = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnLapPengunjung = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnLapTransaksi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnBackup = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnKeluar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homepage5.png"))); // NOI18N

        jMenu1.setText("Data Master");

        mnBuku.setText("Data Buku");
        mnBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBukuActionPerformed(evt);
            }
        });
        jMenu1.add(mnBuku);
        jMenu1.add(jSeparator5);

        mnPeminjaman.setText("Data Peminjaman Buku");
        mnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPeminjamanActionPerformed(evt);
            }
        });
        jMenu1.add(mnPeminjaman);

        mnPengemballian.setText("Data Pengembalian Buku");
        mnPengemballian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPengemballianActionPerformed(evt);
            }
        });
        jMenu1.add(mnPengemballian);
        jMenu1.add(jSeparator2);

        mnPengunjung.setText("Data Pengunjung Perpustakaan");
        mnPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPengunjungActionPerformed(evt);
            }
        });
        jMenu1.add(mnPengunjung);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        mnTransaksi.setText("Denda Keterlambatan");
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(mnTransaksi);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        mnLapBuku.setText("Data Buku");
        mnLapBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapBukuActionPerformed(evt);
            }
        });
        jMenu3.add(mnLapBuku);
        jMenu3.add(jSeparator3);

        mnLapPeminjaman.setText("Peminjaman Buku");
        mnLapPeminjaman.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                mnLapPeminjamanAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        mnLapPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapPeminjamanActionPerformed(evt);
            }
        });
        jMenu3.add(mnLapPeminjaman);

        mnLapPengembalian.setText("Pengembalian Buku");
        mnLapPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapPengembalianActionPerformed(evt);
            }
        });
        jMenu3.add(mnLapPengembalian);
        jMenu3.add(jSeparator6);

        mnLapPengunjung.setText("Pengunjung Perpustakaan ");
        mnLapPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapPengunjungActionPerformed(evt);
            }
        });
        jMenu3.add(mnLapPengunjung);
        jMenu3.add(jSeparator4);

        mnLapTransaksi.setText("Denda Keterlambatan");
        mnLapTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapTransaksiActionPerformed(evt);
            }
        });
        jMenu3.add(mnLapTransaksi);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Utility");

        mnBackup.setText("BackUp Database");
        mnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBackupActionPerformed(evt);
            }
        });
        jMenu4.add(mnBackup);
        jMenu4.add(jSeparator1);

        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        jMenu4.add(mnKeluar);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBukuActionPerformed
        // TODO add your handling code here:
        new frmBuku().setVisible(true);
    }//GEN-LAST:event_mnBukuActionPerformed

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPengunjungActionPerformed
        // TODO add your handling code here:
        new frmPengunjung().setVisible(true);
    }//GEN-LAST:event_mnPengunjungActionPerformed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed
        // TODO add your handling code here:
        new frmTransaksi().setVisible(true);
    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void mnPengemballianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPengemballianActionPerformed
        // TODO add your handling code here:
        new frmPengembalian().setVisible(true);
    }//GEN-LAST:event_mnPengemballianActionPerformed

    private void mnLapPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapPeminjamanActionPerformed
        // TODO add your handling code here:
        new frmLapPeminjaman().setVisible(true);
    }//GEN-LAST:event_mnLapPeminjamanActionPerformed

    private void mnLapPeminjamanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mnLapPeminjamanAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_mnLapPeminjamanAncestorAdded

    private void mnLapPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapPengembalianActionPerformed
        // TODO add your handling code here:
        new frmLapPengembalian().setVisible(true);
    }//GEN-LAST:event_mnLapPengembalianActionPerformed

    private void mnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBackupActionPerformed
        // TODO add your handling code here:
        new frmBackup().setVisible(true);
    }//GEN-LAST:event_mnBackupActionPerformed

    private void mnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPeminjamanActionPerformed
        // TODO add your handling code here:
        new frmPeminjaman().setVisible(true);
    }//GEN-LAST:event_mnPeminjamanActionPerformed

    private void mnLapPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapPengunjungActionPerformed
        // TODO add your handling code here:
        new frmLapPengunjung().setVisible(true);
    }//GEN-LAST:event_mnLapPengunjungActionPerformed

    private void mnLapTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapTransaksiActionPerformed
        // TODO add your handling code here:
        new frmLapTransaksi().setVisible(true);
    }//GEN-LAST:event_mnLapTransaksiActionPerformed

    private void mnLapBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapBukuActionPerformed
        // TODO add your handling code here:
        new frmLapBuku().setVisible(true);
    }//GEN-LAST:event_mnLapBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem mnBackup;
    private javax.swing.JMenuItem mnBuku;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnLapBuku;
    private javax.swing.JMenuItem mnLapPeminjaman;
    private javax.swing.JMenuItem mnLapPengembalian;
    private javax.swing.JMenuItem mnLapPengunjung;
    private javax.swing.JMenuItem mnLapTransaksi;
    private javax.swing.JMenuItem mnPeminjaman;
    private javax.swing.JMenuItem mnPengemballian;
    private javax.swing.JMenuItem mnPengunjung;
    private javax.swing.JMenuItem mnTransaksi;
    // End of variables declaration//GEN-END:variables
}